### ISSUE TITLE
Cannot build, raylib not available?

### ISSUE THREAD

**Issue by dtomvan** [tsoding/tic-tac-toe-fortran-raylib#1]
Hi, I believe the dependency listing isn't correct or exhaustive.

Steps to reproduce:
```bash
$ sudo pacman -Syu gcc-fortran raylib
$ ./build.sh
```

Logs: https://paste.rs/9B9LI.txt

Maybe your bindings don't work well with the builtin Arch Linux distribution of raylib? Or am I doing something wrong?

**Comment by rexim** [comment]
@dtomvan hi! What's the version of gfortran you use?

**Comment by dtomvan** [comment]
Hi, to answer your question, I've included the output for `expac '%n-%v' gcc gcc-fortran raylib; echo -n '\n'; gfortran -v`:
```
gcc-13.1.1-1
gcc-fortran-13.1.1-1
raylib-4.5.0-2

Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/13.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,objc,obj-c++ --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.1.1 20230429 (GCC)
```

**Comment by rexim** [comment]
Nah, it's too much effort for me to try to reproduce on my setup, sorry.

So the problem is 100% not in Raylib. Don't worry about it.

It comes from the `color` macro that's defined in [macros.h](https://github.com/tsoding/tic-tac-toe-fortran-raylib/blob/2cf12de4b1c103c4dbec4b6469285cb55150a7ef/src/macros.h). For some reason your version of gfortran does not like that we pass BOZ literals (it's the hex values that look like `z'FF0000FF'`) to the first argument of the [TRANSFER](https://gcc.gnu.org/onlinedocs/gfortran/TRANSFER.html) function.

I have no idea why that could be the case. I know nothing about Fortran. I'm using it for less than a week. :D

**Comment by rexim** [comment]
Oh, and if it's useful for some reason. My gfortran is 8.3.0. Cause I'm on old Debian stable.

**Comment by dtomvan** [comment]
Alright, I will try it in a docker container or just downgrade my gfortran. I'll get back to you then, cheers!

**Comment by rexim** [comment]
Good luck, my friend! It would be better to figure out how to make the code work on all versions of the compiler, but if this is a more convenient solution for you, go ahead! :+1:

**Comment by petergr20** [comment]
you need to change all line  with color like ex:

integer(c_int32_t), parameter :: restart_button_color    = color(z'FFEEEEEE')
by this 
integer(c_int32_t), parameter :: restart_button_color    = color(int(z'FFEEEEEE'))

and it compile

**Comment by rexim** [comment]
@dtomvan I think we figured it out in #2 Could you please check the latest version?

**Comment by petergr20** [comment]
Thé patch works fine 👌thx

____       ____
  /    )     (    \
/    (  ^_^  )    \
|  {   \('v')/   }  |
|   {   /   \   }   |
|_)(   /\   /\   )(_|
|)  (_ | \|/  |_)  (|
'     "--^^^^--"     '

Le mer. 12 juil. 2023 à 23:29, Alexey Kutepov ***@***.***> a
écrit :

**Comment by dtomvan** [comment]
@rexim Works now, thank you! Sorry for the late response.
