### ISSUE TITLE
AI gives up mid game

### ISSUE THREAD

**Issue by Porem5002** [tsoding/tic-tac-toe-fortran-raylib#3]
I encontered this bug while replicating the situation described in the first TODO of the ai module file, where the ai would not take the shortest path to victory.

Basically what I discovered is that if the board is in the state described: 
![1](https://github.com/tsoding/tic-tac-toe-fortran-raylib/assets/90862885/516d2915-13fe-4dd2-8509-1bda9ff64f16)
And you then enable the X's ai, the new ai will not play and the game will end immediatly:
![2](https://github.com/tsoding/tic-tac-toe-fortran-raylib/assets/90862885/fc33c853-f18f-4530-97b8-7deab61509bb)

**Comment by rexim** [comment]
Yeah, I don't really know what it should do in case it can't find any move where it would at least tie. Just make a losing move anyway? Probably. That would not end the game in such a weird manner at least.

**Comment by Porem5002** [comment]
I think the AI should at least finish the game, for consistency. And if it is sure it will lose, it should at least try to stay alive for as long as possible.
